name: whystartup
layout_spectrum: 0.15256469136424544
typography_spectrum: 0.16438718627338011
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#C0A0A0'
    - '#401020'
    - '#408888'
    - '#A83048'
    - '#000000'
  brandStrength: 0.5243451955214019
  lightness: 0.6851506774418621
  saturation: 0.8340364357749687
  rhythmicContrast: 0.9831652698092136
purpose: []
title: WhyStartup?
author:
  name: WhyStartup
  url: 'http://whystartup.co'
  email: whystartup@gmail.com
content_rating:
  adult: false
