name: whystartup
favicon: null
layout_spectrum: 0.15256469136424544
typography_spectrum: 0.16438718627338011
title: WhyStartup?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0A0A0'
    - '#401020'
    - '#408888'
    - '#A83048'
    - '#000000'
  brandStrength: 0.5243451955214019
  lightness: 0.6851506774418621
  saturation: 0.8340364357749687
  rhythmicContrast: 0.9831652698092136
purpose:
  - name: null
    item: null
    url: null
